name: Remove old artifacts

on:
  schedule:
    # Every hour
    - cron: '0,10,20,30,40,50 * * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '10 seconds'
