name: Remove old artifacts

on:
  schedule:
    # Every hour
    - cron: '23/30 * * * *'
    
jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '10 minutes'
